// Generates speaking.html from data/appearances.yaml.
//
//   node tools/build_speaking.mjs
//
// speaking.html is output, not source. Edit the YAML, run this, commit both.
// Podcasts appear once they have a url; talks always appear.

import { readFileSync, writeFileSync } from 'node:fs'
import { parse } from 'yaml'

const entries = parse(readFileSync('data/appearances.yaml', 'utf8'))

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
const when = (d) => {
  const [y, m, day] = String(d).split('-').map(Number)
  return `${MONTHS[m - 1]} ${day}, ${y}`
}

const newest = (a, b) => String(b.date).localeCompare(String(a.date))

// A title links to its url when there is one, and sits plain when there isn't.
const titleHtml = (e) =>
  e.url ? `<a href="${esc(e.url)}">${esc(e.title)}</a>` : `<em>${esc(e.title)}</em>`

const row = (e, trailing = '') =>
  `    <li><span class="when">${when(e.date)}</span><span class="what">` +
  `<strong>${esc(e.org)}</strong>${e.location && e.location !== 'virtual' ? `, ${esc(e.location)}` : ''}` +
  ` &mdash; ${titleHtml(e)}${trailing}</span></li>`

const list = (rows) => `<ul class="clean">\n${rows.join('\n')}\n  </ul>`

const talks = entries.filter((e) => e.kind === 'talk').sort(newest)
const pods = entries.filter((e) => e.kind === 'podcast' && e.url).sort(newest)
const asGuest = pods.filter((e) => e.role !== 'guest host')
const asHost = pods.filter((e) => e.role === 'guest host')

// Roles worth naming inline. "guest" is the default and goes unsaid.
const note = (e) => (e.role === 'co-host' ? ' <em>(co-host)</em>' : '')
const hostNote = (e) => (e.counterpart ? ` <em>(interviewing ${esc(e.counterpart)})</em>` : '')

const shows = new Set(pods.map((e) => e.org)).size

const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ramona C. Truta</title>
<meta name="description" content="Conference talks and podcast appearances.">
<link rel="stylesheet" href="style.css"></head><body>
<!-- Generated by tools/build_speaking.mjs from data/appearances.yaml. Do not edit by hand. -->
<nav class="topnav"><div class="wrap">
  <a class="brand" href="index.html">Ramona C. Truta</a>
  <span class="navlinks">
    <a href="work.html">Work</a>
    <a href="teaching.html">Teaching</a>
    <a href="speaking.html" class="here">Speaking</a>
    <a href="writing.html">Writing</a>
    <a href="contact.html">Contact</a>
  </span>
</div></nav>
<nav class="subnav"><div class="wrap">
  <a href="#talks">Talks</a>
  <a href="#podcasts">Podcasts</a>
</div></nav>
<section id="talks"><div class="wrap"><h2>Talks</h2>${list(talks.map((e) => row(e)))}</div></section>
<section id="podcasts"><div class="wrap"><h2>Podcasts</h2>
  <p class="lede">${pods.length} episodes across ${shows} shows.</p>
  <h3>As guest</h3>${list(asGuest.map((e) => row(e, note(e))))}
  <h3>As guest host</h3>${list(asHost.map((e) => row(e, hostNote(e))))}
</div></section>
<footer><div class="wrap"><span>&copy; 2025&ndash;2026 Ramona C. Truta &middot; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="license">CC BY-NC-SA 4.0</a></span><a href="contact.html">Contact</a></div></footer>
</body></html>
`

writeFileSync('speaking.html', html)
console.log(`speaking.html: ${talks.length} talks, ${pods.length} episodes, ${shows} shows`)
