"""Apply data/TAGS.yaml to the pages, and build tags.html from it.

    python3 tools/build_tags.py

A tag is a claim that two pieces of work share something. Until it resolves to
the full list of work carrying it, nobody can check that claim. This writes the
tag rows into the pages from one vocabulary, and builds the index they point at.

Fails loudly on a tag that is not in the vocabulary, and on a project id in the
pages that the vocabulary does not cover. Idempotent.
"""
import html
import pathlib
import re
import sys
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGES = ["work.html", "teaching.html"]
SPEC = ROOT / "data" / "TAGS.yaml"


def parse_tags_yaml(text):
    """Minimal reader for this file's shape — no third-party dependency."""
    vocab, projects, section, facet = {}, {}, None, None
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip())
        line = raw.strip()
        if indent == 0 and line.endswith(":"):
            section = line[:-1]
            continue
        if section == "vocabulary":
            if indent == 2 and line.endswith(":"):
                facet = line[:-1]
                continue
            if indent == 4:
                term = line.split(":", 1)[0].strip()
                vocab[term] = facet
        elif section == "projects" and indent == 2:
            pid, rest = line.split(":", 1)
            projects[pid.strip()] = [
                t.strip() for t in rest.strip().strip("[]").split(",") if t.strip()
            ]
    return vocab, projects


vocab, projects = parse_tags_yaml(SPEC.read_text())

unknown = {t: p for p, ts in projects.items() for t in ts if t not in vocab}
if unknown:
    sys.exit(
        "tags not in the vocabulary — add them to data/TAGS.yaml first:\n  "
        + "\n  ".join(f"{t}  (on {p})" for t, p in unknown.items())
    )


def slug(tag):
    return re.sub(r"[^a-z0-9]+", "-", tag.lower()).strip("-")


def row(tags):
    cells = "".join(
        f'<a class="tag" href="tags.html#{slug(t)}">{html.escape(t)}</a>' for t in tags
    )
    return f'<div class="tags">{cells}</div>'


# ---- write the tag rows into the pages -------------------------------------

index = defaultdict(list)
seen = set()

for name in PAGES:
    page = ROOT / name
    text = page.read_text()

    def replace(block):
        pid = block.group(1)
        body = block.group(2)
        seen.add(pid)
        if pid not in projects:
            return block.group(0)
        heading = re.search(r"<h3[^>]*>(.*?)</h3>", body, re.S)
        raw = heading.group(1) if heading else pid
        # the metadata span describes the file, not the work — keep it out of the title
        raw = re.sub(r'<span class="meta">.*?</span>', "", raw, flags=re.S)
        title = html.unescape(re.sub(r"<[^>]+>", " ", raw))
        title = re.sub(r"\s+", " ", title).strip()
        for t in projects[pid]:
            index[t].append((name, pid, title))
        body = re.sub(r'<div class="tags">.*?</div>', row(projects[pid]), body, flags=re.S)
        return f'<div class="proj" id="{pid}">{body}'

    text = re.sub(
        r'<div class="proj" id="([^"]*)">(.*?)(?=<div class="proj"|</div></section>)',
        replace,
        text,
        flags=re.S,
    )
    page.write_text(text)

missing = sorted(seen - set(projects))
if missing:
    sys.exit("projects in the pages with no entry in data/TAGS.yaml:\n  " + "\n  ".join(missing))

# ---- the index page --------------------------------------------------------

facets = defaultdict(list)
for tag, facet in vocab.items():
    if tag in index:
        facets[facet].append(tag)


def entries(items):
    return "\n".join(
        f'    <li><span class="what"><a href="{pg}#{pid}">{html.escape(title)}</a></span></li>'
        for pg, pid, title in items
    )


def facet_html(facet):
    out = []
    for tag in sorted(facets[facet], key=str.lower):
        items = index[tag]
        out.append(
            f'  <h3 id="{slug(tag)}">{html.escape(tag)}'
            f' <span class="tag-count">{len(items)}</span></h3>\n'
            f'  <ul class="clean">\n{entries(items)}\n  </ul>'
        )
    return "\n\n".join(out)


total = sum(len(v) for v in index.values())
doc = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ramona C. Truta &mdash; Index</title>
<meta name="description" content="Every tag used on this site, and all the work it points to.">
<link rel="stylesheet" href="style.css"></head><body>
<!-- Generated by tools/build_tags.py from data/TAGS.yaml. Do not edit by hand. -->
<nav class="topnav"><div class="wrap">
  <a class="brand" href="index.html">Ramona C. Truta</a>
  <span class="navlinks">
    <a href="work.html">Work</a>
    <a href="teaching.html">Teaching</a>
    <a href="speaking.html">Speaking</a>
    <a href="writing.html">Writing</a>
    <a href="contact.html">Contact</a>
  </span>
</div></nav>
<nav class="subnav" id="top"><div class="wrap">
  <a href="#discipline">Discipline</a>
  <a href="#method">Method</a>
  <a href="#technology">Technology</a>
  <a href="work.html">Back to Work</a>
</div></nav>

<section><div class="wrap">
  <h2 id="discipline">Discipline</h2>
  <p class="lede">What the work is about. The number beside each tag is how many pieces of
  work carry it &mdash; a one means the term names something that has happened once so far.</p>

{facet_html("discipline")}

  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>

<section><div class="wrap">
  <h2 id="method">Method</h2>
  <p class="lede">How a claim was established, rather than what it was about.</p>

{facet_html("method")}

  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>

<section><div class="wrap">
  <h2 id="technology">Technology</h2>
  <p class="lede">What it was built with.</p>

{facet_html("technology")}

  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>

<footer><div class="wrap"><span>&copy; 2025&ndash;2026 Ramona C. Truta &middot; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="license">CC BY-NC-SA 4.0</a></span><a href="contact.html">Contact</a></div></footer>
</body></html>
"""

(ROOT / "tags.html").write_text(doc)
print(f"tags.html: {len(index)} tags across {len(projects)} projects, {total} links")
for facet in ("discipline", "method", "technology"):
    print(f"  {facet:12} {len(facets[facet])} tags")
