"""Write the site navigation into every page from one definition.

    python3 tools/build_nav.py

The nav was duplicated across six pages and three generators, and had already
drifted. This is the only place it is defined. Run it after adding a page.

It writes two things from the same config.yaml entry: the nav bar, and the
one-line description that appears as the lede at the top of that page. The
home page renders the same descriptions beside the links, so the summary a
reader sees on the home page and the summary on the page itself cannot
disagree.

Generated pages (speaking, writing, tags) are rewritten by their own tools too,
so this runs over whatever is on disk and their templates carry the same list —
if they disagree, this file wins and the generator should be corrected.
"""
import html
import pathlib
import re
from config_loader import load_config

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = load_config()

NAV = [(item["label"], item["href"]) for item in CONFIG["navigation"]]
PAGES = [item["href"] for item in CONFIG["navigation"]] + ["index.html"]
BRAND = CONFIG["site"]["author"].get("name", CONFIG["site"].get("title", "Home"))


def nav_html(current):
    links = "\n".join(
        f'    <a href="{href}"{" class=\"here\"" if href == current else ""}>{label}</a>'
        for label, href in NAV
    )
    return f"""<nav class="topnav"><div class="wrap">
  <a class="brand" href="index.html">{BRAND}</a>
  <span class="navlinks">
{links}
    <button type="button" class="searchbtn" aria-label="Search this site" title="Search this site (⌘K)" data-search-open>
      <svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor"
           stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="M20 20l-4.2-4.2"/></svg>
    </button>
  </span>
</div></nav>"""

LEDES = {item["href"]: item["description"] for item in CONFIG["navigation"]}


def lede_html(description):
    return (f'<!-- lede:start -->\n'
            f'<section class="pagelede"><div class="wrap">'
            f'<p class="lede">{html.escape(description)}</p></div></section>\n'
            f'<!-- lede:end -->')


def write_descriptions(text, description):
    """The meta, og and twitter descriptions, all from the one config.yaml line.

    speaking.html is generated by a separate Node tool that carried its own
    copy, and it had already drifted from the rest.
    """
    esc = html.escape(description, quote=True)
    for pattern in (r'(<meta name="description" content=")[^"]*(">)',
                    r'(<meta property="og:description" content=")[^"]*(">)',
                    r'(<meta name="twitter:description" content=")[^"]*(">)'):
        text = re.sub(pattern, lambda m: m.group(1) + esc + m.group(2), text, count=1)
    return text


def write_lede(text, description):
    """Replace the lede block, or insert one after the sub-nav (else the nav)."""
    block = lede_html(description)
    if "<!-- lede:start -->" in text:
        return re.sub(r"<!-- lede:start -->.*?<!-- lede:end -->", lambda _: block, text, count=1, flags=re.S)
    anchor = re.search(r'<nav class="subnav".*?</nav>', text, re.S) or \
             re.search(r'<nav class="topnav">.*?</nav>', text, re.S)
    return text[:anchor.end()] + "\n" + block + text[anchor.end():]


changed = 0
for name in PAGES:
    page = ROOT / name
    if not page.exists():
        print(f"  skipped (missing): {name}")
        continue
    text = page.read_text()
    new = re.sub(
        r'<nav class="topnav">.*?</nav>', nav_html(name), text, count=1, flags=re.S
    )
    if name in LEDES:                      # index.html has no nav entry of its own
        new = write_lede(new, LEDES[name])
        new = write_descriptions(new, LEDES[name])
    if new != text:
        page.write_text(new)
        changed += 1

print(f"nav + lede + descriptions written into {changed} of {len(PAGES)} pages, {len(NAV)} links")
