"""Build tags.html from the tags already written into the pages, and make every
tag on those pages a link into it.

    python3 tools/build_tags.py

A tag is a claim that two pieces of work share something. Until it is a link,
nobody can check that claim. This turns the tag vocabulary into an index with
referential integrity: every tag resolves to the complete list of work carrying
it, and a tag carried by only one thing says so plainly.

Idempotent — re-running after editing a page rewrites both sides.
"""
import html
import pathlib
import re
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGES = ["work.html", "teaching.html", "writing.html", "speaking.html"]


def slug(tag):
    return re.sub(r"[^a-z0-9]+", "-", tag.lower()).strip("-")


# tag -> list of (page, anchor, title)
index = defaultdict(list)

for name in PAGES:
    page = ROOT / name
    if not page.exists():
        continue
    text = page.read_text()

    # each project block: its id, its heading, and the tags inside it
    for block in re.finditer(
        r'<div class="proj"(?: id="([^"]*)")?>(.*?)(?=<div class="proj"|</div></section>)',
        text,
        re.S,
    ):
        anchor, body = block.group(1) or "", block.group(2)
        heading = re.search(r"<h3[^>]*>(.*?)</h3>", body, re.S)
        title = re.sub(r"<[^>]+>", "", heading.group(1)).strip() if heading else name
        title = html.unescape(re.sub(r"\s+", " ", title))
        for tag in re.findall(r'<(?:span|a)[^>]*class="tag"[^>]*>(.*?)</(?:span|a)>', body):
            entry = (name, anchor, title)
            if entry not in index[html.unescape(tag)]:
                index[html.unescape(tag)].append(entry)

    # tags that sit outside a project block belong to the page itself
    stripped = re.sub(
        r'<div class="proj".*?(?=<div class="proj"|</div></section>)', "", text, flags=re.S
    )
    page_title = re.search(r"<h2[^>]*>(.*?)</h2>", stripped, re.S)
    ptitle = (
        html.unescape(re.sub(r"<[^>]+>", "", page_title.group(1)).strip())
        if page_title
        else name
    )
    for tag in re.findall(r'<(?:span|a)[^>]*class="tag"[^>]*>(.*?)</(?:span|a)>', stripped):
        entry = (name, "", ptitle)
        if entry not in index[html.unescape(tag)]:
            index[html.unescape(tag)].append(entry)

# ---- rewrite every tag on every page into a link into the index -------------

for name in PAGES:
    page = ROOT / name
    if not page.exists():
        continue
    text = page.read_text()

    def linkify(m):
        tag = html.unescape(m.group(1))
        return f'<a class="tag" href="tags.html#{slug(tag)}">{m.group(1)}</a>'

    text = re.sub(r'<span class="tag">(.*?)</span>', linkify, text)
    text = re.sub(r'<a class="tag" href="tags.html#[^"]*">(.*?)</a>', linkify, text)
    page.write_text(text)

# ---- the index page --------------------------------------------------------

shared = {t: v for t, v in index.items() if len(v) > 1}
single = {t: v for t, v in index.items() if len(v) == 1}


def entries(items):
    out = []
    for pg, anchor, title in items:
        href = f"{pg}#{anchor}" if anchor else pg
        out.append(
            f'    <li><span class="what"><a href="{href}">{html.escape(title)}</a>'
            f' <em>{pg.replace(".html", "")}</em></span></li>'
        )
    return "\n".join(out)


def group(d):
    out = []
    for tag in sorted(d, key=str.lower):
        out.append(
            f'  <h3 id="{slug(tag)}">{html.escape(tag)} '
            f'<span class="tag-count">{len(d[tag])}</span></h3>\n'
            f'  <ul class="clean">\n{entries(d[tag])}\n  </ul>'
        )
    return "\n\n".join(out)


doc = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ramona C. Truta &mdash; Index</title>
<meta name="description" content="Every tag used across this site, and the work it points to.">
<link rel="stylesheet" href="style.css"></head><body>
<!-- Generated by tools/build_tags.py from the tags on the other pages. Do not edit by hand. -->
<nav class="topnav"><div class="wrap">
  <a class="brand" href="index.html">Ramona C. Truta</a>
  <span class="navlinks">
    <a href="work.html">Work</a>
    <a href="teaching.html">Teaching</a>
    <a href="speaking.html">Speaking</a>
    <a href="writing.html">Writing</a>
    <a href="contact.html">Contact</a>
  </span>
</div></nav>
<nav class="subnav" id="top"><div class="wrap">
  <a href="#shared">Shared</a>
  <a href="#once">Used once</a>
</div></nav>

<section><div class="wrap">
  <h2 id="shared">What connects the work</h2>
  <p class="lede">{len(shared)} of {len(index)} tags appear on more than one piece of work.
  These are the threads.</p>

{group(shared)}

  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>

<section><div class="wrap">
  <h2 id="once">Used once</h2>
  <p class="lede">{len(single)} tags name something specific to a single piece of work.
  Listed so the vocabulary is visible rather than implied.</p>

{group(single)}

  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>

<footer><div class="wrap"><span>&copy; 2025&ndash;2026 Ramona C. Truta &middot; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="license">CC BY-NC-SA 4.0</a></span><a href="contact.html">Contact</a></div></footer>
</body></html>
"""

(ROOT / "tags.html").write_text(doc)
print(f"tags.html: {len(index)} tags, {len(shared)} shared, {len(single)} used once")
