// Generates speaking.html from data/appearances.yaml and config.yaml with zero dependencies.
import { readFileSync, writeFileSync } from 'node:fs';

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function parseSimpleYamlDict(text) {
  const dict = {};
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*(\w+):\s*[\"']?([^\"'\n]+)[\"']?/);
    if (m) {
      dict[m[1]] = m[2].trim();
    }
  }
  return dict;
}

function parseYamlList(text) {
  const blocks = text.split(/\n(?=- id:)/).filter(b => b.trim().startsWith('- id:'));
  return blocks.map(block => {
    const entry = {};
    const lines = block.split('\n');
    for (const line of lines) {
      const m = line.match(/^\s*(?:-\s*)?(\w+):\s*(.+?)\s*(?:#.*)?$/);
      if (m) {
        let val = m[2].trim();
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        entry[m[1]] = val;
      }
    }
    return entry;
  });
}

const config = parseSimpleYamlDict(readFileSync('config.yaml', 'utf8'));
const AUTHOR = esc(config.name || config.title || 'Author');
const SITE_TITLE = esc(config.title || AUTHOR);
const SITE_URL = config.url || '';
const SITE_IMAGE = esc(config.image || `${SITE_URL}/assets/photo.jpg`);
const LICENSE_LABEL = esc(config.copyright_license || 'CC BY-NC-SA 4.0');
const LICENSE_URL = esc(config.copyright_license_url || 'https://creativecommons.org/licenses/by-nc-sa/4.0/');

const entries = parseYamlList(readFileSync('data/appearances.yaml', 'utf8'));

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const when = (d) => {
  const [y, m, day] = String(d).split('-').map(Number);
  return `${MONTHS[m - 1]} ${day}, ${y}`;
};

const newest = (a, b) => String(b.date).localeCompare(String(a.date));

const titleHtml = (e) =>
  e.url ? `<a href="${esc(e.url)}" target="_blank" rel="noopener">${esc(e.title)}</a>` : `<em>${esc(e.title)}</em>`;

const row = (e, trailing = '') =>
  `    <li id="${esc(e.id)}"><span class="when">${when(e.date)}</span><span class="what">` +
  `<strong>${esc(e.org)}</strong>${e.location && e.location !== 'virtual' ? `, ${esc(e.location)}` : ''}` +
  ` &mdash; ${titleHtml(e)}${trailing}</span></li>`;

const list = (rows) => `<ul class="clean">\n${rows.join('\n')}\n  </ul>`;

const talks = entries.filter((e) => e.kind === 'talk').sort(newest);
const pods = entries.filter((e) => e.kind === 'podcast' && e.url).sort(newest);
const asGuest = pods.filter((e) => e.role !== 'guest host');
const asHost = pods.filter((e) => e.role === 'guest host');

const note = (e) => (e.role === 'co-host' ? ' <em>(co-host)</em>' : '');
const hostNote = (e) => (e.counterpart ? ` <em>(interviewing ${esc(e.counterpart)})</em>` : '');

const shows = new Set(pods.map((e) => e.org)).size;

const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${AUTHOR} &mdash; Speaking</title>
<meta name="description" content="Conference talks and podcast appearances.">
<link rel="icon" type="image/x-icon" href="assets/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="assets/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">
<meta property="og:site_name" content="${SITE_TITLE}">
<meta property="og:type" content="website">
<meta property="og:title" content="Speaking &mdash; ${AUTHOR}">
<meta property="og:description" content="Conference talks and podcast appearances as guest and guest host.">
<meta property="og:image" content="${SITE_IMAGE}">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Speaking &mdash; ${AUTHOR}">
<meta name="twitter:description" content="Conference talks and podcast appearances as guest and guest host.">
<meta name="twitter:image" content="${SITE_IMAGE}">
<link rel="stylesheet" href="style.css"></head><body>
<!-- Generated by tools/build_speaking.mjs from data/appearances.yaml. Do not edit by hand. -->
<nav class="topnav"><div class="wrap">
  <a class="brand" href="index.html">${AUTHOR}</a>
  <span class="navlinks">
    <a href="work.html">Work</a>
    <a href="teaching.html">Teaching</a>
    <a href="speaking.html" class="here">Speaking</a>
    <a href="writing.html">Writing</a>
    <a href="tags.html">Index</a>
    <a href="contact.html">Contact</a>
  </span>
</div></nav>
<nav class="subnav" id="top"><div class="wrap">
  <a href="#talks">Talks</a>
  <a href="#podcasts">Podcasts</a>
  <a href="#guest-host">As guest host</a>
  <a href="#as-guest">As guest</a>
</div></nav>
<section id="talks"><div class="wrap"><h2>Talks</h2>${list(talks.map((e) => row(e)))}
  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>
<section id="podcasts"><div class="wrap"><h2>Podcasts</h2>
  <p class="lede">${pods.length} episodes across ${shows} shows.</p>
  <h3 id="guest-host">As guest host</h3>
  <p class="lede">One of the biggest joys in my life is showing up for my friends. Celebrating them.</p>
  ${list(asHost.map((e) => row(e, hostNote(e))))}
  <h3 id="as-guest">As guest</h3>${list(asGuest.map((e) => row(e, note(e))))}
  <p class="totop"><a href="#top">&uarr; Top</a></p>
</div></section>
<footer><div class="wrap"><span>&copy; 2025&ndash;2026 ${AUTHOR} &middot; <a href="${LICENSE_URL}" rel="license">${LICENSE_LABEL}</a> &middot; <a href="contact.html">Contact</a></span></div></footer>
</body></html>
`;

writeFileSync('speaking.html', html);
console.log(`speaking.html: ${talks.length} talks, ${pods.length} episodes, ${shows} shows`);
