"""Generate the GitHub profile README from the same data as the website.

    python3 tools/build_github_readme.py          # write ~/Projects/rctruta/README.md
    python3 tools/build_github_readme.py --stdout # print it instead

The profile README was the last hand-written page of the portfolio, and it had
already drifted from the site: it carried its own bio, its own writing list and
its own speaking list, and it featured two repositories that were not pinned
while pinning two that it did not mention.

The website and the profile are not two portfolios. They are two projections of
one dataset: the site shows everything, the profile shows the work that has
code. A project appears here when its work.yaml entry has a github.com link.
"""
import pathlib
import re
import sys
from config_loader import load_config
from model import load_taxonomy, load_work_sections, load_articles, load_appearances, load_home
from bio import as_markdown

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = pathlib.Path.home() / "Projects" / "rctruta" / "README.md"
CONFIG = load_config()
A = CONFIG["site"]["author"]
SITE = CONFIG["site"]["url"].rstrip("/")

ARTICLES_SHOWN = 5
MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

vocab = load_taxonomy()
sections = load_work_sections(vocab)
home = load_home()

bio_markdown = as_markdown(home.bio)

profile_yaml = (ROOT / "data" / "github_profile.yaml").read_text()
FEATURED_REPO = re.search(r'^featured_repo: "(.*)"', profile_yaml, re.M).group(1)
featured = re.search(r"^featured: \|\n((?:  .*\n|\n)*)", profile_yaml, re.M)
featured = "\n".join(l[2:] for l in featured.group(1).splitlines()).strip() if featured else ""


def blurb(item) -> str:
    """The item's own one-liner, else its first sentence.

    Truncating to a first sentence inverted a finding once — podcast-rag read
    as "no error of any kind", which is the opposite of what the study found —
    so an item can carry its own summary and these do.
    """
    if item.summary:
        return item.summary
    text = " ".join(item.description.strip().split())
    # a description that opens by repeating the repository name in bold
    text = re.sub(r"^\*\*[^*]+\*\* — ", "", text)
    return re.split(r"(?<=[.!?]) ", text)[0]


def repo_url(item):
    for link in item.links:
        if "github.com" in link.url:
            return link.url
    return None


def when(d: str) -> str:
    y, m, day = d.split("-")
    return f"{MONTHS[int(m) - 1]} {int(day)}, {y}"


# --- projects, grouped the way the website groups them --------------------
project_blocks = []
for sec in sections:
    rows = [(i, repo_url(i)) for i in sec.items]
    rows = [(i, u) for i, u in rows if u and u.rstrip("/") != FEATURED_REPO.rstrip("/")]
    if not rows:
        continue
    lines = "\n".join(
        f"| [**{u.rstrip('/').split('/')[-1]}**]({u}) | {blurb(i)} "
        f"[→]({SITE}/work.html#{i.id}) |"
        for i, u in rows
    )
    project_blocks.append(f"#### {sec.title}\n\n| | |\n|---|---|\n{lines}")

# --- writing and speaking, newest first -----------------------------------
articles = load_articles(vocab)[:ARTICLES_SHOWN]
writing = "\n".join(f"- [{a.title}]({a.url}) — {a.argues}" for a in articles)

talks = [a for a in load_appearances(vocab) if a.kind == "talk"][:4]
speaking = "\n".join(
    f"- **{t.org}** — *{t.title}*" + (f" · {t.location}" if t.location else "") + f" · {when(t.date)}"
    for t in talks
)

doc = f"""### {A['name']}

{bio_markdown}

[Portfolio]({SITE}) · [Writing]({A['substack']}) · [LinkedIn]({A['linkedin']}) · [ORCID]({A['orcid']})

---

{featured}

---

### Projects

{chr(10).join(f'{b}{chr(10)}' for b in project_blocks)}
---

### Writing

{writing}

[Everything →]({SITE}/writing.html)

### Speaking

{speaking}

[Everything →]({SITE}/speaking.html)

<!-- Generated by tools/build_github_readme.py in rctruta/rctruta.github.io,
     from the same data as the website. Edit the data, not this file. -->
"""

if "--stdout" in sys.argv:
    print(doc)
else:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(doc, encoding="utf-8")
    shown = sum(len(re.findall(r"^\| \[", b, re.M)) for b in project_blocks)
    print(f"{OUT}: {shown} repositories, {len(articles)} articles, {len(talks)} talks.")
    bare = [i.id for s_ in sections for i in s_.items
            if repo_url(i) and not i.summary and repo_url(i).rstrip("/") != FEATURED_REPO.rstrip("/")]
    if bare:
        print("  no summary, using the first sentence: " + ", ".join(bare))
