"""Generate the interview prep sheet from the site's own data.

    python3 tools/build_prep_sheet.py

Writes ~/Projects/Interview/Prep/PREP.md. Not part of the website: it is not
in the repository and it is not published.

Everything here is derived. Nothing is a suggested answer, because a suggested
answer is a script and a script is what falls apart under a follow-up question.
What it gives her per project is:

  the claim        what the site says, in one line
  the evidence     the links a reader can follow, and the registered facts
  the numbers      every figure in the entry, marked registered or not
  not claimed      what the entry deliberately does not say

That last column is the one that matters under pressure. The failure mode in an
interview is not blanking, it is answering past what the evidence supports —
which is the same defect this repository's gates exist to catch in writing.
"""
import pathlib
import re
import sys

from model import (load_taxonomy, load_work_sections, load_articles,
                   load_appearances)

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = pathlib.Path.home() / "Projects" / "Interview" / "Prep" / "PREP.md"
FACTS = pathlib.Path.home() / "claude-docs-allowed" / "Resume" / ".claims" / "FACTS.yaml"

# Model names carry version numbers that are not claims: GPT-4.1, Gemini 3.1
# Pro, Claude Opus 4.6. Blanked before scanning, or the sheet tells her to
# justify the "4.1" in GPT-4.1.
MODEL_NAMES = re.compile(
    r"\b(?:GPT|Claude|Gemini|Llama|Mistral|Opus|Sonnet|Haiku|Command|DuckDB|"
    r"PostgreSQL|Python|gemma)[\w.-]*\s?[\d.]*\b", re.I)

# a number worth asking about, not a year or a version fragment
NUM = re.compile(r"(?<![\w.])\d[\d,]*(?:\.\d+)?\s?(?:x|×|%|\+)?(?![\w.])")
IGNORE_NUMS = {str(y) for y in range(1850, 2031)} | {str(n) for n in range(0, 11)}


def registered_claims():
    """Numbers registered in FACTS.yaml, and the context each was registered for."""
    if not FACTS.exists():
        return {}
    out, claim = {}, None
    for line in FACTS.read_text().splitlines():
        m = re.match(r'\s+claim:\s*"(.+)"', line)
        if m:
            claim = m.group(1)
        m = re.match(r'\s+context:\s*"(.+)"', line)
        if m and claim:
            for tok in re.findall(r"[\d][\d,.]*\+?%?x?", claim):
                out[tok.rstrip(".")] = m.group(1)
            claim = None
    return out


def numbers_in(text, registered):
    seen, rows = set(), []
    text = MODEL_NAMES.sub(" ", text or "")
    for raw in NUM.findall(text):
        n = raw.strip().rstrip(",")   # "1852," in a list of census years is a year
        if n in IGNORE_NUMS or n in seen:
            continue
        seen.add(n)
        src = next((registered[k] for k in registered if k.startswith(n) or n == k), None)
        rows.append((n, src))
    return rows


def not_claimed(item, text):
    """What the entry deliberately does not say — read off the entry itself."""
    out = []
    if not item.links:
        out.append("No public artifact is linked. The claim rests on your account of it; "
                   "say so plainly rather than implying a reader could go and check.")
    for note in item.notes:
        t = (note.text or "")
        if re.search(r"held|not publish|private|disclosure", t, re.I):
            out.append("Something is deliberately held back: " + t)
        elif re.search(r"presented at|published", t, re.I):
            out.append("Public record exists: " + t)
    for phrase, why in [
        (r"\bnot a (finding|claim)\b", "The entry already states this is not a finding. Do not upgrade it."),
        (r"\bretract", "This entry records a retraction. Lead with it; it is the strongest thing in it."),
        (r"\bdid not\b|\bcould not\b|\bfailed\b", "The entry records a negative result. That is the result, not a shortfall."),
        (r"\bDNF\b", "DNF rows are findings recorded as data, not crashes."),
        (r"held back|not public|stays private|only thing held",
         "Part of this is deliberately unpublished. Say what is held and why, "
         "rather than letting them assume everything is open."),
        (r"\bnot a performance\b|rather than timing|not a benchmark",
         "This is a correctness study, not a speed one. The distinction is the point."),
    ]:
        if re.search(phrase, text, re.I):
            out.append(why)
    return out


def main():
    vocab = load_taxonomy()
    sections = load_work_sections(vocab)
    registered = registered_claims()
    articles = load_articles(vocab)
    talks = [a for a in load_appearances(vocab) if a.kind == "talk"]

    L = []
    L.append("# Interview prep — generated from the site's own data\n")
    L.append("Generated by `tools/build_prep_sheet.py` in rctruta.github.io. Rebuild it after\n"
             "changing `data/work.yaml`; do not edit this file, the edits will be lost.\n")
    L.append("**The rule this sheet exists to serve:** if you cannot say what a project is in\n"
             "three sentences, it should not be on the site. Everything below is on the site.\n")
    L.append(f"{sum(len(s.items) for s in sections)} projects · {len(articles)} articles · "
             f"{len(talks)} talks\n")
    L.append("---\n")

    for sec in sections:
        L.append(f"## {sec.title}\n")
        L.append(f"*{sec.summary}*\n")
        for item in sec.items:
            text = " ".join((item.description or "").split())
            L.append(f"### {item.title}\n")
            if item.blurb:
                L.append(f"**In one line.** {item.blurb}\n")
            else:
                first = re.split(r"(?<=[.!?]) ", text)[0] if text else ""
                L.append(f"**In one line.** {first}\n")

            if item.links:
                L.append("**Evidence they can open.**\n")
                for lnk in item.links:
                    L.append(f"- [{lnk.text}]({lnk.url})")
                L.append("")
            else:
                L.append("**Evidence they can open.** None linked.\n")

            nums = numbers_in(text, registered)
            if nums:
                L.append("**Numbers in this entry.**\n")
                L.append("| figure | registered against |")
                L.append("|---|---|")
                for n, src in nums:
                    L.append(f"| {n} | {src if src else '**not registered** — be ready to say where it comes from, or do not say it'} |")
                L.append("")

            gaps = not_claimed(item, text)
            if gaps:
                L.append("**What this entry does not claim.**\n")
                for g in gaps:
                    L.append(f"- {g}")
                L.append("")

            L.append(f"<sub>`{item.id}` · {', '.join(item.tags)}</sub>\n")
        L.append("---\n")

    L.append("## If someone checks the site's security grade\n")
    L.append("""SSL Labs gives https://ramonactruta.com a **B**. So does
`rctruta.github.io` — measured on the same 8 endpoints, 4 IPv4 and 4 IPv6. It
is GitHub Pages' TLS termination, not anything in the repository, and no change
to the site, the DNS or the domain settings moves it.

The cap is one thing: `forwardSecrecy: 1`, meaning some of SSL Labs' simulated
browsers negotiate a cipher suite without forward secrecy. GitHub still offers
one for old clients.

What the same scan found: **TLS 1.2 and 1.3 only** — no TLS 1.0 or 1.1 — and
not vulnerable to BEAST, POODLE, Heartbleed, FREAK or Logjam, with no RC4.

The answer, if asked: that is GitHub Pages' TLS configuration, and `github.io`
scores identically. Checking and knowing why is the better answer; an A would
only mean a host where you control the cipher list.

The certificate renews itself. GitHub Pages issues and renews Let's Encrypt
certificates automatically while the DNS stays pointed at GitHub and the domain
stays verified — both true. Nothing to do in November.\n""")

    L.append("## Talks, in case they ask what you have said in public\n")
    for t in talks:
        where = f", {t.location}" if t.location else ""
        L.append(f"- **{t.org}**{where} — *{t.title}* · {t.date}")
    L.append("")

    banned = re.findall(r'- pattern: "(.+?)"\n\s+reason: "(.+?)"', FACTS.read_text()) if FACTS.exists() else []
    L.append(f"## {len(banned)} things never to say\n")
    L.append("Read off the banned list in `FACTS.yaml`. These were wrong once and are\n"
             "blocked in writing; nothing blocks them out loud.\n")
    for pat, reason in banned:
        L.append(f"- **{pat}** — {reason}")
    L.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    unreg = sum(1 for s in sections for i in s.items
                for n, src in numbers_in(" ".join((i.description or "").split()), registered)
                if not src)
    print(f"{OUT}: {sum(len(s.items) for s in sections)} projects, "
          f"{unreg} unregistered figures flagged.")


if __name__ == "__main__":
    main()
