"""Write the site navigation into every page from one definition.

    python3 tools/build_nav.py

The nav was duplicated across six pages and three generators, and had already
drifted. This is the only place it is defined. Run it after adding a page.

It writes three things from the same config.yaml entry: the nav link, the
description that appears when the reader hovers that link, and the page's meta
description. The home page renders the same descriptions beside the links, so
what a reader is told about a page cannot depend on where they are told it.

Generated pages (speaking, writing, tags) are rewritten by their own tools too,
so this runs over whatever is on disk and their templates carry the same list —
if they disagree, this file wins and the generator should be corrected.
"""
import html
import pathlib
import re
from config_loader import load_config

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = load_config()

NAV = [(item["label"], item["href"], item["description"]) for item in CONFIG["navigation"]]
PAGES = [item["href"] for item in CONFIG["navigation"]] + ["index.html"]
BRAND = CONFIG["site"]["author"].get("name", CONFIG["site"].get("title", "Home"))
SEARCH = html.escape(CONFIG["site"].get("search_label", "Search this site"), quote=True)


def nav_html(current):
    links = "\n".join(
        f'    <a href="{href}"{" class=\"here\"" if href == current else ""}'
        f' data-tip="{html.escape(tip, quote=True)}">{label}</a>'
        for label, href, tip in NAV
    )
    return f"""<nav class="topnav"><div class="wrap">
  <a class="brand" href="index.html" title="Home" aria-label="Home">{BRAND}</a>
  <span class="navlinks">
{links}
    <button type="button" class="searchbtn" aria-label="{SEARCH}" data-tip="{SEARCH}" data-search-open>
      <svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor"
           stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="M20 20l-4.2-4.2"/></svg>
    </button>
  </span>
</div></nav>"""

DESCRIPTIONS = {item["href"]: item["description"] for item in CONFIG["navigation"]}


def write_descriptions(text, description):
    """The meta, og and twitter descriptions, all from the one config.yaml line.

    speaking.html is generated by a separate Node tool that carried its own
    copy, and it had already drifted from the rest.
    """
    esc = html.escape(description, quote=True)
    for pattern in (r'(<meta name="description" content=")[^"]*(">)',
                    r'(<meta property="og:description" content=")[^"]*(">)',
                    r'(<meta name="twitter:description" content=")[^"]*(">)'):
        text = re.sub(pattern, lambda m: m.group(1) + esc + m.group(2), text, count=1)
    return text


def drop_lede(text):
    """Remove the lede block. The description is a hover on the nav link now."""
    return re.sub(r"\n?<!-- lede:start -->.*?<!-- lede:end -->\n?", "\n", text, count=1, flags=re.S)


changed = 0
for name in PAGES:
    page = ROOT / name
    if not page.exists():
        print(f"  skipped (missing): {name}")
        continue
    text = page.read_text()
    new = re.sub(
        r'<nav class="topnav">.*?</nav>', nav_html(name), text, count=1, flags=re.S
    )
    new = drop_lede(new)
    if name in DESCRIPTIONS:                      # index.html has no nav entry of its own
        new = write_descriptions(new, DESCRIPTIONS[name])
    if new != text:
        page.write_text(new)
        changed += 1

print(f"nav + hover + descriptions written into {changed} of {len(PAGES)} pages, {len(NAV)} links")
